swagger:
  resources:
    - name: School
      url: http://localhost:9011/school/v2/api-docs
      version: 1.0
    - name: Organization
      url: http://localhost:9012/organization/v2/api-docs
      version: 1.0
